# Generated by Django 5.1.3 on 2025-01-14 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeeNotes', '0007_feenote_date_created_feenote_fee_note_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='feenote',
            name='travel_detail',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
