# Generated by Django 5.1.3 on 2025-01-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0007_staff_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='last_seen',
            field=models.DateTimeField(null=True),
        ),
    ]
