# Generated by Django 5.1.3 on 2025-01-14 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cases', '0010_case_customer_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='customer_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
