# Generated by Django 5.1.3 on 2025-01-14 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cases', '0011_alter_case_customer_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='customer_reference',
            field=models.CharField(default='Not Advised', max_length=100),
        ),
    ]
