# Generated by Django 5.1.3 on 2025-01-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reminders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='run_until',
            field=models.DateField(null=True),
        ),
    ]
