# Generated by Django 5.1.3 on 2025-01-04 08:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Staff', '0007_staff_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attatchment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='attatchments/')),
            ],
        ),
        migrations.CreateModel(
            name='ExpenditurePurpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expenditure', models.CharField(choices=[('Fuel', 'Fuel'), ('Transport', 'Transport'), ('Meals', 'Meals'), ('Out of Office', 'Out of Office'), ('Destination', 'Destination'), ('Others', 'Others')], max_length=100)),
                ('specification', models.CharField(max_length=100)),
                ('daily_amount', models.PositiveIntegerField()),
                ('days', models.PositiveIntegerField()),
                ('total', models.PositiveIntegerField()),
                ('attatchment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='StaffReimbursement.attatchment')),
            ],
        ),
        migrations.CreateModel(
            name='StaffReimbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('description_of_assignment', models.TextField()),
                ('total', models.PositiveIntegerField()),
                ('date_approved', models.DateTimeField()),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Staff.staff')),
                ('expenditures', models.ManyToManyField(to='StaffReimbursement.expenditurepurpose')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reimbursement_staff', to='Staff.staff')),
            ],
        ),
        migrations.AddField(
            model_name='expenditurepurpose',
            name='reimbursement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StaffReimbursement.staffreimbursement'),
        ),
    ]
