# Generated by Django 5.1.3 on 2025-01-04 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StaffReimbursement', '0002_alter_staffreimbursement_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenditurepurpose',
            name='attatchment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='StaffReimbursement.attatchment'),
        ),
        migrations.AlterField(
            model_name='expenditurepurpose',
            name='total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='staffreimbursement',
            name='expenditures',
            field=models.ManyToManyField(blank=True, to='StaffReimbursement.expenditurepurpose'),
        ),
    ]
