name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.CLAIMS_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        # Add the server's SSH key to known_hosts
        ssh-keyscan -p 4242 claimsug.com >> ~/.ssh/known_hosts
        # Disable host key checking to avoid any issues with the key mismatch
        echo -e "Host *\n  StrictHostKeyChecking no\n  UserKnownHostsFile=/dev/null" >> ~/.ssh/config

    - name: Deploy to Server
      run: |
        ssh -o ConnectTimeout=30 -p 4242 claimsug@claimsug.com "cd /home1/claimsug/projects/claims-uganda && git pull"
